---
title: "CANDO+P Reactor In-cycle Visualizations"
output: html_notebook
---
This notebook produces plots and figures for CANDO+P reactor data from in-cycle sampling

Code set up
```{r setup}
# working directory - wherever cycle results are saved
file_path <- "C:/Users/mckyf/Box/CANDO+P and N2O/CANDO+P Reactor 2021/Operation and Logs"
knitr::opts_knit$set(root.dir = normalizePath(file_path)) # sets all notebook chunks to have this path

# packages
library(readxl)
library(ggplot2)
library(tidyverse)

colors <- c("#F78464","#2E294E","#1B998B","08716A")
```

Data import
```{r message=FALSE, warning=FALSE}
# import cycle and hach sensor data
in_cycle <- "./Performance logs/cycle_results.xlsx"
in_hach <- Sys.glob(paths="./Sensor logs/Hach/hach_dl*.csv")

data_cycle <- read_excel(in_cycle, sheet="master")
data_hach <- bind_rows(lapply(in_hach,read.csv))

# clean up data for merging later
data_cycle <- subset(data_cycle,select=-c(date,time))

data_hach <- data_hach[!duplicated(data_hach),]
data_hach$date_time <- as.POSIXct(data_hach$date_time, tz="GMT", format="%Y/%m/%d %H:%M:%S")

# split data by date
split_cycle <- split(data_cycle, as.Date(data_cycle$date_time))
split_hach <- split(data_hach, as.Date(data_hach$date_time))
```

21-07-15
```{r}
# data cleaning
# filter hach data by cycle time

cycle_hach <- split_hach$'2021-07-14'  %>%
  filter(date_time >= as.POSIXct("2021-07-14 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-07-14 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-07-14`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210714 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210714 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-07-14 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgN/L","NO3_mgN/L","OP_mgP/L")
params_no_no3 <- c("NO2_mgN/L","OP_mgP/L")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ylim(0,50) + 
  ggtitle("In-cycle nutrient sampling 7/14/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=45, label="anaerobic") +
  annotate("text", x=3.5, y=45, label="anoxic") + 
  annotate("text", x=6, y=45, label="aerobic") +
  theme_classic() + 
  scale_color_manual(values=colors) + 
  scale_shape_manual(values=c(15,17,19))

# ggsave("cycle_210707.png", height=4, width=7, units="in", scale=0.8)

```


21-07-07
```{r}
# data cleaning
# filter hach data by cycle time

cycle_hach <- split_hach$'2021-07-07'  %>%
  filter(date_time >= as.POSIXct("2021-07-07 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-07-07 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-07-07`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210707 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210707 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-07-07 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgN/L","NO3_mgN/L","OP_mgP/L")
params_no_no3 <- c("NO2_mgN/L","OP_mgP/L")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ylim(0,50) + 
  ggtitle("In-cycle nutrient sampling 7/7/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=45, label="anaerobic") +
  annotate("text", x=3.5, y=45, label="anoxic") + 
  annotate("text", x=6, y=45, label="aerobic") +
  theme_classic() + 
  scale_color_manual(values=colors) + 
  scale_shape_manual(values=c(15,17,19))

# ggsave("cycle_210707.png", height=4, width=7, units="in", scale=0.8)

```


21-06-30
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-30' %>%
  filter(date_time >= as.POSIXct("2021-06-30 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-30 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-30`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210630 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210630_long <- cycle_210630 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-30 08:23:00", tz="GMT")

# time value
cycle_210630_long$time_diff <- as.numeric(difftime(cycle_210630_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgN/L","NO2+NO3_mgN/L","OP_mgP/L")
params_no_no3 <- c("NO2_mgN/L","OP_mgP/L")

# plotting
# NO2, PO4
ggplot(data=subset(cycle_210630_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/30/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=63, label="anaerobic") +
  annotate("text", x=3.5, y=63, label="anoxic") + 
  annotate("text", x=6, y=63, label="aerobic") +
  theme_classic() + 
  scale_color_manual(values=c(colors[1],colors[3])) + 
  scale_shape_manual(values=c(15,19))

# ggsave("cycle_210630.png", height=4, width=7, units="in", scale=0.8)
```


21-06-16
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-16' %>%
  filter(date_time >= as.POSIXct("2021-06-16 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-16 15:00:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-16`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210616 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210616_long <- cycle_210616 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-16 08:23:00", tz="GMT")

# time value
cycle_210616_long$time_diff <- as.numeric(difftime(cycle_210616_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgN/L","NO2+NO3_mgN/L","OP_mgP/L")
params_no_no3 <- c("NO2_mgN/L","OP_mgP/L")

# plotting
# NO2, PO4
ggplot(data=subset(cycle_210616_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/16/21") + 
  ylim(0,35) +
  geom_vline(xintercept=2.1, color="grey") + 
  geom_vline(xintercept=5.617, color="grey") + 
  annotate("text", x=1, y=35, label="anaerobic") +
  annotate("text", x=3.8, y=35, label="anoxic") + 
  annotate("text", x=6.5, y=35, label="aerobic") +
  theme_classic()

```


21-06-09
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-09' %>%
  filter(date_time >= as.POSIXct("2021-06-09 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-09 15:00:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-09`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210609 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210609_long <- cycle_210609 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-09 08:23:00", tz="GMT")

# time value
cycle_210609_long$time_diff <- as.numeric(difftime(cycle_210609_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgN/L","NO2+NO3_mgN/L","OP_mgP/L")
params_no_no3 <- c("NO2_mgN/L","OP_mgP/L")

# plotting

# all nutrients
# ggplot(data=subset(cycle_210609_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
#   geom_point(aes(col=parameter)) +
#   xlab("Hours") + 
#   ylab("Concentration - mgN/L or mgP/L") +
#   ggtitle("In-cycle nutrient sampling 6/9/21") + 
#   ylim(0,35) +
#   geom_vline(xintercept=2.1, color="grey") + 
#   geom_vline(xintercept=5.617, color="grey") + 
#   theme_classic()

# NO2, PO4
ggplot(data=subset(cycle_210609_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/9/21") + 
  ylim(0,35) +
  geom_vline(xintercept=2.1, color="grey") + 
  geom_vline(xintercept=5.617, color="grey") + 
  annotate("text", x=1, y=35, label="anaerobic") +
  annotate("text", x=3.8, y=35, label="anoxic") + 
  annotate("text", x=6.5, y=35, label="aerobic") +
  theme_classic()

```


21-06-03 - anaerobic sampling only
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-03' %>%
  filter(date_time >= as.POSIXct("2021-06-03 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-03 15:00:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-03`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210603 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210603_long <- cycle_210603 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-03 08:23:00", tz="GMT")

# time value
cycle_210603_long$time_diff <- as.numeric(difftime(cycle_210603_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgN/L","NO2+NO3_mgN/L","OP_mgP/L")
params_no_no3 <- c("NO2_mgN/L","OP_mgP/L")

# plotting

# all nutrients
# ggplot(data=subset(cycle_210609_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
#   geom_point(aes(col=parameter)) +
#   xlab("Hours") + 
#   ylab("Concentration - mgN/L or mgP/L") +
#   ggtitle("In-cycle nutrient sampling 6/9/21") + 
#   ylim(0,35) +
#   geom_vline(xintercept=2.1, color="grey") + 
#   geom_vline(xintercept=5.617, color="grey") + 
#   theme_classic()

# NO2, PO4
ggplot(data=subset(cycle_210603_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/3/21 - anaerobic phase only") + 
  ylim(0,30) +
  xlim(0,2) +
  theme_classic()
```



