---
title: "CANDO+P Reactor In-cycle Visualizations"
---
This notebook produces plots and figures for CANDO+P reactor data from in-cycle sampling. Using this as of 10/14/21.

Code set up
```{r setup}
# working directory - wherever cycle results are saved
file_path <- "C:/Users/mckyf/Box/CANDO+P and N2O/CANDO+P Reactor 2021/Operation and Logs"
knitr::opts_knit$set(root.dir = normalizePath(file_path)) # sets all notebook chunks to have this path

# packages
library(readxl)
library(ggplot2)
library(tidyverse)
library(zoo)
library(lubridate)

# custom scale color and labels so all plots are uniform
scale_color_cycle <- function(...){
  ggplot2:::manual_scale("color", values = setNames(c("#AA5042","#2E294E","#1B998B","#F6AE2D",
                                  "#AB99AD","#ADE48B","#E5989B","#8D99AE","#FB5012"),
                                  c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL",
                                  "OP_mgPL","do_ppm","ph","orp","N2O_mgNL")), 
                                  labels = setNames(c("NO2 mgNL","NO2+NO3 mgNL","NO3 mgNL",
                                   "NH3 mgNL", "OP mgPL","DO mgO2L","pH","ORP mV","N2O mgNL"),
                                  c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL",
                                    "OP_mgPL","do_ppm","ph","orp","N2O_mgNL")),
        ...
    )
}

shape_values = setNames(c(19,18,17,15,16,5,4,3,20),
                        c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL","OP_mgPL",
                         "do_ppm","ph","orp","N2O_mgNL"))

shape_labels = setNames(c("NO2 mgNL","NO2+NO3 mgNL","NO3 mgNL","NH3 mgNL","OP mgPL",
                          "DO mgO2L","pH","ORP mV","N2O mgNL"), 
                        c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL","OP_mgPL",
                          "do_ppm","ph","orp","N2O_mgNL"))

# add these to every ggplot:  
  # scale_color_cycle() + 
  # scale_shape_manual(values=shape_values,labels=shape_labels)
```

Data import - cycle data
```{r message=FALSE, warning=FALSE}
# import
sheet_name = "21.10.05"
in_skalar <- "./Performance logs/cycle_results.xlsx"
cycle_skalar <- read_excel(in_skalar, sheet=sheet_name)

# clean
cycle_skalar <- subset(cycle_skalar,select=-c(date,time,phase)) # remove date,time,phase columns

```


Data import - sensor data
```{r}
# import sensor data and clean

in_hach <- Sys.glob(paths="./Sensor logs/Hach/sc1000_dl_21.10.14.csv")
in_n2o <- Sys.glob(paths="./Sensor logs/Unisense/n2o_211014.xlsx")

data_hach <- bind_rows(lapply(in_hach,read.csv))
data_n2o <- bind_rows(lapply(in_n2o,read_excel,na="NA"))

# clean up data for merging later
data_n2o <- subset(data_n2o,select=-c(date,time))

data_hach <- data_hach[!duplicated(data_hach),] # remove overlapping data
data_n2o <- data_n2o[!duplicated(data_n2o),]

data_hach$date_time <- ymd_hms(data_hach$date_time, tz="GMT")  # date time
data_n2o$date_time <- ymd_hms(data_n2o$date_time, tz="GMT")

data_n2o$N2O_mgNL_raw <- as.numeric(data_n2o$N2O_mgNL_raw) # numeric
data_n2o$temp <- as.numeric(data_n2o$temp)

# subsetting n2o
data_n2o <- data_n2o %>%
  mutate(N2O_mgNL_temp = N2O_mgNL_raw/(1.033^(21-temp))) %>%
  filter(row_number() %% 30 == 0) %>%
  rename(N2O_mgNL=N2O_mgNL_temp)

# split data by date
split_hach <- split(data_hach, as.Date(data_hach$date_time))
split_n2o <- split(data_n2o, as.Date(data_n2o$date_time))
```


Merging data and plotting - 10/13/21
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-10-13'  %>%
  filter(date_time >= as.POSIXct("2021-10-13 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-10-13 14:40:00", tz="GMT"))

cycle_n2o <- split_n2o$'2021-10-13'  %>%
  filter(date_time >= as.POSIXct("2021-10-13 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-10-13 14:40:00", tz="GMT"))


# merge cycle sampling and hach data into one dataframe
cycle <- cycle_skalar # uncomment/comment if you only want the skalar results plotted
cycle <- merge(cycle_hach, cycle_skalar, by="date_time", all=TRUE) 
cycle <- merge(cycle, cycle_n2o, by="date_time", all=TRUE)

# long format
cycle_long <- cycle %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-10-13 08:22:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO3_mgNL","OP_mgPL","NO2_mgNL","N2O_mgNL")

# plotting
ylim_val = 50
ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,ylim_val) + 
  ggtitle("In-cycle nutrient sampling 10/13/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=ylim_val, label="anaerobic") +
  annotate("text", x=3.5, y=ylim_val, label="anoxic") + 
  annotate("text", x=6, y=ylim_val, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_211013.png", height=4, width=7, units="in", scale=0.8)
```

10/05/21
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-10-05'  %>%
  filter(date_time >= as.POSIXct("2021-10-05 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-10-05 14:40:00", tz="GMT"))

cycle_n2o <- split_n2o$'2021-10-05'  %>%
  filter(date_time >= as.POSIXct("2021-10-05 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-10-05 14:40:00", tz="GMT"))


# merge cycle sampling and hach data into one dataframe
cycle <- merge(cycle_hach, cycle_skalar, by="date_time", all=TRUE) 
cycle <- merge(cycle, cycle_n2o, by="date_time", all=TRUE)

# long format
cycle_long <- cycle %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-10-05 08:22:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO3_mgNL","OP_mgPL","NO2_mgNL","N2O_mgNL")

# plotting
ylim_val = 30

ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,ylim_val) + 
  ggtitle("In-cycle nutrient sampling 10/05/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=ylim_val, label="anaerobic") +
  annotate("text", x=3.5, y=ylim_val, label="anoxic") + 
  annotate("text", x=6, y=ylim_val, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_211005.png", height=4, width=7, units="in", scale=0.8)
```

