---
title: "CANDO+P Reactor In-cycle Visualizations"
output: html_notebook
---
This notebook produces plots and figures for CANDO+P reactor data from in-cycle sampling

Code set up
```{r setup}
# working directory - wherever cycle results are saved
file_path <- "C:/Users/mckyf/Box/CANDO+P and N2O/CANDO+P Reactor 2021/Operation and Logs"
knitr::opts_knit$set(root.dir = normalizePath(file_path)) # sets all notebook chunks to have this path

# packages
library(readxl)
library(ggplot2)
library(tidyverse)
library(zoo)

# custom scale color and labels so all plots are uniform
scale_color_cycle <- function(...){
  ggplot2:::manual_scale("color", values = setNames(c("#AA5042","#2E294E","#1B998B","#F6AE2D",
                                  "#AB99AD","#ADE48B","#E5989B","#8D99AE","#FB5012"),
                                  c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL",
                                  "OP_mgPL","do_ppm","ph","orp","N2O_mgNL")), 
                                  labels = setNames(c("NO2 mgNL","NO2+NO3 mgNL","NO3 mgNL",
                                   "NH3 mgNL", "OP mgPL","DO mgO2L","pH","ORP mV","N2O mgNL"),
                                  c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL",
                                    "OP_mgPL","do_ppm","ph","orp","N2O_mgNL")),
        ...
    )
}

shape_values = setNames(c(19,18,17,15,16,5,4,3,20),
                        c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL","OP_mgPL",
                         "do_ppm","ph","orp","N2O_mgNL"))

shape_labels = setNames(c("NO2 mgNL","NO2+NO3 mgNL","NO3 mgNL","NH3 mgNL","OP mgPL",
                          "DO mgO2L","pH","ORP mV","N2O mgNL"), 
                        c("NO2_mgNL","NO2+NO3_mgNL","NO3_mgNL","NH3_mgNL","OP_mgPL",
                          "do_ppm","ph","orp","N2O_mgNL"))

# add these to every ggplot:  
  # scale_color_cycle() + 
  # scale_shape_manual(values=shape_values,labels=shape_labels)
```

Data import
```{r message=FALSE, warning=FALSE}
# import cycle and hach sensor data
in_cycle <- "./Performance logs/cycle_results.xlsx"
# in_hach <- Sys.glob(paths="./Sensor logs/Hach/hach_dl*.csv")
# in_n2o <- Sys.glob(paths="./Sensor logs/Unisense/n2o*.xlsx")

in_hach <- Sys.glob(paths="./Sensor logs/Hach/hach_dl_21.9.10.csv")
in_n2o <- Sys.glob(paths="./Sensor logs/Unisense/n2o_210910.xlsx")

data_cycle <- read_excel(in_cycle, sheet="master")
data_hach <- bind_rows(lapply(in_hach,read.csv))
data_n2o <- bind_rows(lapply(in_n2o,read_excel,na="NA"))

# clean up data for merging later
data_cycle <- subset(data_cycle,select=-c(date,time)) # remove date and time columns
data_n2o <- subset(data_n2o,select=-c(date,time))

data_hach <- data_hach[!duplicated(data_hach),] # remove overlapping data
data_n2o <- data_n2o[!duplicated(data_n2o),]

data_hach$date_time <- as.POSIXct(data_hach$date_time, tz="GMT", format="%Y/%m/%d %H:%M:%S") # date time
data_n2o$date_time <- as.POSIXct(data_n2o$date_time, tz="GMT", format="%Y/%m/%d %H:%M:%S")

data_n2o$N2O_mgNL_raw <- as.numeric(data_n2o$N2O_mgNL_raw) # numeric
data_n2o$temp <- as.numeric(data_n2o$temp)

# subsetting n2o
data_n2o <- data_n2o %>%
  mutate(N2O_mgNL_temp = N2O_mgNL_raw/(1.033^(21-temp))) %>%
  filter(row_number() %% 30 == 0) %>%
  rename(N2O_mgNL=N2O_mgNL_temp)

# rolling average
# data_n2o <- data_n2o %>% 
#   mutate(N2O_mgNL=rollapply(N2O_mgNL_temp,100,FUN=mean,partial=TRUE))


# split data by date
split_cycle <- split(data_cycle, as.Date(data_cycle$date_time))
split_hach <- split(data_hach, as.Date(data_hach$date_time))
split_n2o <- split(data_n2o, as.Date(data_n2o$date_time))

```

21-09-08
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-09-08'  %>%
  filter(date_time >= as.POSIXct("2021-09-08 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-09-08 14:40:00", tz="GMT"))

cycle_n2o <- split_n2o$'2021-09-08'  %>%
  filter(date_time >= as.POSIXct("2021-09-08 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-09-08 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-09-08`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210908 <- merge(cycle_hach, cycle, by="date_time", all=TRUE) 
cycle_210908 <- merge(cycle_210908, cycle_n2o, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210908 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-09-08 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO3_mgNL","OP_mgPL","N2O_mgNL","NO2_mgNL")

# plotting

ylim_val = 25

ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,ylim_val) + 
  ggtitle("In-cycle nutrient sampling 9/08/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=ylim_val, label="anaerobic") +
  annotate("text", x=3.5, y=ylim_val, label="anoxic") + 
  annotate("text", x=6, y=ylim_val, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210908.png", height=4, width=7, units="in", scale=0.8)
```


21-09-01
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-09-01'  %>%
  filter(date_time >= as.POSIXct("2021-09-01 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-09-01 14:40:00", tz="GMT"))

cycle_n2o <- split_n2o$'2021-09-01'  %>%
  filter(date_time >= as.POSIXct("2021-09-01 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-09-01 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-09-01`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210901 <- merge(cycle_hach, cycle, by="date_time", all=TRUE) 
cycle_210901 <- merge(cycle_210901, cycle_n2o,by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210901 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-09-01 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2+NO3_mgNL","OP_mgPL","N2O_mgNL")

# plotting

ylim_val = 25

ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,ylim_val) + 
  ggtitle("In-cycle nutrient sampling 9/1/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=ylim_val, label="anaerobic") +
  annotate("text", x=3.5, y=ylim_val, label="anoxic") + 
  annotate("text", x=6, y=ylim_val, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210901.png", height=4, width=7, units="in", scale=0.8)
```

21-08-25
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-08-25'  %>%
  filter(date_time >= as.POSIXct("2021-08-25 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-08-25 14:40:00", tz="GMT"))

cycle_n2o <- split_n2o$'2021-08-25'  %>%
  filter(date_time >= as.POSIXct("2021-08-25 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-08-25 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-08-25`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210825 <- merge(cycle_hach, cycle, by="date_time", all=TRUE) 
cycle_210825 <- merge(cycle_210825, cycle_n2o,by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210825 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-08-25 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO3_mgNL","OP_mgPL","N2O_mgNL")

# plotting

ylim_val = 25

ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,ylim_val) + 
  ggtitle("In-cycle nutrient sampling 8/25/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=ylim_val, label="anaerobic") +
  annotate("text", x=3.5, y=ylim_val, label="anoxic") + 
  annotate("text", x=6, y=ylim_val, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210825.png", height=4, width=7, units="in", scale=0.8)
```


21-08-18
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-08-18'  %>%
  filter(date_time >= as.POSIXct("2021-08-18 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-08-18 14:40:00", tz="GMT"))

cycle_n2o <- split_n2o$'2021-08-18'  %>%
  filter(date_time >= as.POSIXct("2021-08-18 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-08-18 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-08-18`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210818 <- merge(cycle_hach, cycle, by="date_time", all=TRUE) 
cycle_210818 <- merge(cycle_210818, cycle_n2o,by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210818 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-08-18 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO3_mgNL","OP_mgPL","NH3_mgNL","N2O_mgNL")

# plotting

ylim_val = 25

ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,ylim_val) + 
  ggtitle("In-cycle nutrient sampling 8/18/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=ylim_val, label="anaerobic") +
  annotate("text", x=3.5, y=ylim_val, label="anoxic") + 
  annotate("text", x=6, y=ylim_val, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210818.png", height=4, width=7, units="in", scale=0.8)

```

21-08-10
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-08-10'  %>%
  filter(date_time >= as.POSIXct("2021-08-10 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-08-10 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-08-10`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210810 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210810 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-08-10 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO3_mgNL","OP_mgPL","NH3_mgNL","do_ppm")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,15) + 
  ggtitle("In-cycle nutrient sampling 8/10/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=15, label="anaerobic") +
  annotate("text", x=3.5, y=15, label="anoxic") + 
  annotate("text", x=6, y=15, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210810.png", height=4, width=7, units="in", scale=0.8)

```



21-08-04
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-08-04'  %>%
  filter(date_time >= as.POSIXct("2021-08-04 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-08-04 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-08-04`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210804 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210804 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-08-04 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO3_mgNL","OP_mgPL","NH3_mgNL")
params_nitrogen <- c("NO2_mgNL","NO3_mgNL","NH3_mgNL")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,25) + 
  ggtitle("In-cycle nutrient sampling 8/04/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=25, label="anaerobic") +
  annotate("text", x=3.5, y=25, label="anoxic") + 
  annotate("text", x=6, y=25, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210804.png", height=4, width=7, units="in", scale=0.8)

ggplot(data=subset(cycle_long, parameter %in% params_nitrogen), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mgN/L") +
  ylim(0,10) + 
  ggtitle("In-cycle nutrient sampling - nitrogen species - 8/04/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=10, label="anaerobic") +
  annotate("text", x=3.5, y=10, label="anoxic") + 
  annotate("text", x=6, y=10, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210804_nitrogen.png", height=4, width=7, units="in", scale=0.8)


```


21-07-28
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-07-28'  %>%
  filter(date_time >= as.POSIXct("2021-07-28 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-07-28 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-07-28`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210728 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210728 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-07-28 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","OP_mgPL","NH3_mgNL")
params_nitrogen <- c("NO2_mgNL","NO3_mgNL","NH3_mgNL")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,25) + 
  ggtitle("In-cycle nutrient sampling 7/28/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=25, label="anaerobic") +
  annotate("text", x=3.5, y=25, label="anoxic") + 
  annotate("text", x=6, y=25, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210728.png", height=4, width=7, units="in", scale=0.8)

ggplot(data=subset(cycle_long, parameter %in% params_nitrogen), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration mgN/L") +
  ylim(0,6) + 
  ggtitle("In-cycle nutrient sampling - nitrogen species - 7/28/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=6, label="anaerobic") +
  annotate("text", x=3.5, y=6, label="anoxic") + 
  annotate("text", x=6, y=6, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)
ggsave("cycle_210728_nitrogen.png", height=4, width=7, units="in", scale=0.8)


```


21-07-21
```{r}
# data cleaning
# filter hach data by cycle time

cycle_hach <- split_hach$'2021-07-21'  %>%
  filter(date_time >= as.POSIXct("2021-07-21 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-07-21 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-07-21`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210721 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210721 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-07-21 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO3_mgNL","OP_mgPL")
params_no_no3 <- c("NO2_mgNL","OP_mgPL","do_ppm")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter),alpha=0.7) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,40) + 
  ggtitle("In-cycle nutrient sampling 7/21/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=40, label="anaerobic") +
  annotate("text", x=3.5, y=40, label="anoxic") + 
  annotate("text", x=6, y=40, label="aerobic") +
  theme_classic() + 
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)

ggsave("cycle_210721.png", height=4, width=7, units="in", scale=0.8)

```


21-07-14
```{r}
# data cleaning
# filter hach data by cycle time

cycle_hach <- split_hach$'2021-07-14'  %>%
  filter(date_time >= as.POSIXct("2021-07-14 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-07-14 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-07-14`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210714 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210714 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-07-14 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO3_mgNL","OP_mgPL")
params_no_no3 <- c("NO2_mgNL","OP_mgPL","do_ppm")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter),alpha=0.7) +
  xlab("Hours") + 
  ylab("Concentration mg/L") +
  ylim(0,50) + 
  ggtitle("In-cycle nutrient sampling 7/14/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=45, label="anaerobic") +
  annotate("text", x=3.5, y=45, label="anoxic") + 
  annotate("text", x=6, y=45, label="aerobic") +
  theme_classic() +
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)

ggsave("cycle_210714.png", height=4, width=7, units="in", scale=0.8)

```


21-07-07
```{r}
# data cleaning
# filter hach data by cycle time

cycle_hach <- split_hach$'2021-07-07'  %>%
  filter(date_time >= as.POSIXct("2021-07-07 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-07-07 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-07-07`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210707 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_long <- cycle_210707 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-07-07 08:23:00", tz="GMT")

# time value
cycle_long$time_diff <- as.numeric(difftime(cycle_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO3_mgNL","OP_mgPL")
params_no_no3 <- c("NO2_mgNL","OP_mgPL","do_ppm")

# plotting
ggplot(data=subset(cycle_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter),alpha=0.7) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ylim(0,50) + 
  ggtitle("In-cycle nutrient sampling 7/7/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=45, label="anaerobic") +
  annotate("text", x=3.5, y=45, label="anoxic") + 
  annotate("text", x=6, y=45, label="aerobic") +
  theme_classic() +
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)

ggsave("cycle_210707.png", height=4, width=7, units="in", scale=0.8)

```


21-06-30
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-30' %>%
  filter(date_time >= as.POSIXct("2021-06-30 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-30 14:40:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-30`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210630 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210630_long <- cycle_210630 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-30 08:23:00", tz="GMT")

# time value
cycle_210630_long$time_diff <- as.numeric(difftime(cycle_210630_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO2+NO3_mgNL","OP_mgPL")
params_no_no3 <- c("NO2_mgNL","OP_mgPL")

# plotting
# NO2, PO4
ggplot(data=subset(cycle_210630_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/30/21") +
  geom_vline(xintercept=1.78, color="grey") + 
  geom_vline(xintercept=5.28, color="grey") + 
  annotate("text", x=0.75, y=63, label="anaerobic") +
  annotate("text", x=3.5, y=63, label="anoxic") + 
  annotate("text", x=6, y=63, label="aerobic") +
  theme_classic()  +
  scale_color_cycle() + 
  scale_shape_manual(values=shape_values,labels=shape_labels)

ggsave("cycle_210630.png", height=4, width=7, units="in", scale=0.8)
```


21-06-16
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-16' %>%
  filter(date_time >= as.POSIXct("2021-06-16 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-16 15:00:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-16`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210616 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210616_long <- cycle_210616 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-16 08:23:00", tz="GMT")

# time value
cycle_210616_long$time_diff <- as.numeric(difftime(cycle_210616_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO2+NO3_mgNL","OP_mgPL")
params_no_no3 <- c("NO2_mgNL","OP_mgPL")

# plotting
# NO2, PO4
ggplot(data=subset(cycle_210616_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/16/21") + 
  ylim(0,35) +
  geom_vline(xintercept=2.1, color="grey") + 
  geom_vline(xintercept=5.617, color="grey") + 
  annotate("text", x=1, y=35, label="anaerobic") +
  annotate("text", x=3.8, y=35, label="anoxic") + 
  annotate("text", x=6.5, y=35, label="aerobic") +
  theme_classic()

```


21-06-09
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-09' %>%
  filter(date_time >= as.POSIXct("2021-06-09 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-09 15:00:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-09`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210609 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210609_long <- cycle_210609 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-09 08:23:00", tz="GMT")

# time value
cycle_210609_long$time_diff <- as.numeric(difftime(cycle_210609_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO2+NO3_mgNL","OP_mgPL")
params_no_no3 <- c("NO2_mgNL","OP_mgPL")

# plotting

# all nutrients
# ggplot(data=subset(cycle_210609_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
#   geom_point(aes(col=parameter)) +
#   xlab("Hours") + 
#   ylab("Concentration - mgN/L or mgP/L") +
#   ggtitle("In-cycle nutrient sampling 6/9/21") + 
#   ylim(0,35) +
#   geom_vline(xintercept=2.1, color="grey") + 
#   geom_vline(xintercept=5.617, color="grey") + 
#   theme_classic()

# NO2, PO4
ggplot(data=subset(cycle_210609_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/9/21") + 
  ylim(0,35) +
  geom_vline(xintercept=2.1, color="grey") + 
  geom_vline(xintercept=5.617, color="grey") + 
  annotate("text", x=1, y=35, label="anaerobic") +
  annotate("text", x=3.8, y=35, label="anoxic") + 
  annotate("text", x=6.5, y=35, label="aerobic") +
  theme_classic()

```


21-06-03 - anaerobic sampling only
```{r}
# data cleaning
# filter hach data by cycle time
cycle_hach <- split_hach$'2021-06-03' %>%
  filter(date_time >= as.POSIXct("2021-06-03 08:20:00", tz="GMT") & date_time <= as.POSIXct("2021-06-03 15:00:00", tz="GMT"))

# remove phase and hour columns from skalar data
cycle <- subset(split_cycle$`2021-06-03`, select=-c(phase))

# merge cycle sampling and hach data into one dataframe
cycle_210603 <- merge(cycle_hach, cycle, by="date_time", all=TRUE)

# long format
cycle_210603_long <- cycle_210603 %>%
  pivot_longer(!date_time, names_to="parameter", values_to="value")

start_time <- as.POSIXct("2021-06-03 08:23:00", tz="GMT")

# time value
cycle_210603_long$time_diff <- as.numeric(difftime(cycle_210603_long$date_time, start_time, units="hours"))

# specify what to plot
params_to_plot <- c("NO2_mgNL","NO2+NO3_mgNL","OP_mgPL")
params_no_no3 <- c("NO2_mgNL","OP_mgPL")

# plotting

# all nutrients
# ggplot(data=subset(cycle_210609_long, parameter %in% params_to_plot), mapping=aes(time_diff,value)) + 
#   geom_point(aes(col=parameter)) +
#   xlab("Hours") + 
#   ylab("Concentration - mgN/L or mgP/L") +
#   ggtitle("In-cycle nutrient sampling 6/9/21") + 
#   ylim(0,35) +
#   geom_vline(xintercept=2.1, color="grey") + 
#   geom_vline(xintercept=5.617, color="grey") + 
#   theme_classic()

# NO2, PO4
ggplot(data=subset(cycle_210603_long, parameter %in% params_no_no3), mapping=aes(time_diff,value)) + 
  geom_point(aes(col=parameter, shape=parameter)) +
  xlab("Hours") + 
  ylab("Concentration - mgN/L or mgP/L") +
  ggtitle("In-cycle nutrient sampling 6/3/21 - anaerobic phase only") + 
  ylim(0,30) +
  xlim(0,2) +
  theme_classic()
```



